[template]
 src   = "packer.json.tmpl"
 dest  = "/packer/packer.json"
 keys = [
  "/ami/name",
  "/app/version",
  "/aws/default/region",
  "/aws/source/ami",
  "/aws/instance/type",
  "/aws/ssh/username",
  "/aws/security/group/id"
 ]